name: "Branch Protection Ruleset"
target: branch
enforcement: active

conditions:
  ref_name:
    include:
      - "refs/heads/main"

rules:
  - type: pull_request
    parameters:
      dismiss_stale_reviews_on_push: true
      require_code_owner_review: false
      require_last_push_approval: false
      required_approving_review_count: 1
      required_review_thread_resolution: true

  - type: required_status_checks
    parameters:
      strict_required_status_checks_policy: true
      required_status_checks: []

  - type: non_fast_forward
    
  - type: deletion

  - type: creation

bypass_actors:
  - actor_id: 1
    actor_type: RepositoryRole
    bypass_mode: always